apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "maisengasse"
  description: "maisengasse"
  tags:
    - sx
    - template
  links:
    - url: https://grafana.apps.cluster1.mcp.pitagora.at/d/KRlE7mE4z/4-golden-signals-sx-cnp?orgId=1&refresh=5s&var-namespace=suxess-it-prod,qa,dev&var-workload=maisengasse&var-service=maisengasse
      title: Grafana SRE Metrics
      icon: web
    - url: http://maisengasse-suxess-it-prod,qa,dev.apps.cluster1.mcp.pitagora.at
      title: maisengasse Service Route
      icon: web
  annotations:
    github.com/project-slug: phac008/maisengasse-gitops
    backstage.io/kubernetes-id: maisengasse
    kubecost.com/deployment-name: maisengasse
    argocd/app-name: maisengasse-prod,qa,dev
    backstage.io/kubernetes-namespace: suxess-it-prod,qa,dev
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "(tags @> '4GoldenSignals')"
    grafana/overview-dashboard: "https://grafana.apps.cluster1.mcp.pitagora.at/d/KRlE7mE4z/4-golden-signals-sx-cnp?orgId=1&refresh=5s&var-namespace=suxess-it-prod,qa,dev&var-workload=maisengasse&var-service=maisengasse"
spec:
  type: service
  lifecycle: experimental
  owner: group:default/jokl
  system: system:maisengasse
  dependsOn:
    - resource:argocd
