apiVersion: apps/v1
kind: Deployment
metadata:
  name: maisengasse
  namespace: suxess-it-prod,qa,dev
  labels:
    app: maisengasse
    backstage.io/kubernetes-id: maisengasse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maisengasse
  template:
    metadata:
      labels:
        app: maisengasse
        backstage.io/kubernetes-id: maisengasse
    spec:
      containers:
#      - image: quay.io/rbaumgar/monitor-demo-app-jvm
      - image: quay.io/rbaumgar/monitor-demo-app-jvm
        imagePullPolicy: Always
        name: maisengasse