apiVersion: v1
kind: Service
metadata:
  name: maisengasse
  namespace: suxess-it-prod,qa,dev
  labels:
    app: maisengasse
    backstage.io/kubernetes-id: maisengasse
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: maisengasse
  type: ClusterIP